version: "3.1"
services:
  scrobbler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./data.db:/data.db
      - ./oauth.json:/oauth.json
      - ./.env:/.env
